-- MySQL Script generated by MySQL Workbench
-- Mon Mar 29 20:10:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema endereco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `endereco` ;

-- -----------------------------------------------------
-- Schema endereco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `endereco` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci ;
SHOW WARNINGS;
USE `endereco` ;

-- -----------------------------------------------------
-- Table `bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bairro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `bairro` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cidade` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `cep` VARCHAR(10) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `endereco` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `pais` INT NOT NULL,
  `cidade` INT NOT NULL,
  `estado` INT NOT NULL,
  `bairro` INT NOT NULL,
  `rua` INT NOT NULL,
  `cep` VARCHAR(10) NULL,
  PRIMARY KEY (`codigo`, `pais`, `cidade`, `estado`, `bairro`, `rua`),
  CONSTRAINT `fk_endereco_pais`
    FOREIGN KEY (`pais`)
    REFERENCES `pais` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade`)
    REFERENCES `cidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `estado` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`bairro`)
    REFERENCES `bairro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_rua1`
    FOREIGN KEY (`rua`)
    REFERENCES `rua` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_endereco_pais_idx` ON `endereco` (`pais` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_endereco_cidade1_idx` ON `endereco` (`cidade` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_endereco_estado1_idx` ON `endereco` (`estado` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_endereco_bairro1_idx` ON `endereco` (`bairro` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_endereco_rua1_idx` ON `endereco` (`rua` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `estado` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `sigla` VARCHAR(2) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pais` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rua` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rua` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
